sonar.projectKey=jgf-dev_inkstory
sonar.organization=jgf-dev
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.d.ts,**/supabase/types.ts
sonar.cpd.exclusions=**/tests/**,**/*.test.ts,**/*.test.tsx