name: Change Tracking Marker
on:
  release:
    types:
      - published
permissions:
  contents: read
jobs:
  newrelic:
    runs-on: ubuntu-latest
    name: New Relic
    steps:
      - name: New Relic Application Deployment Marker
        uses: newrelic/deployment-marker-action@d88a59ea8f713ad6935e60de27273157790b1e3b # v2.6.2
        with:
          commandType: changeTrackingCreateEvent
          region: EU
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          entitySearch: id = 'ODU3NzkxNHxBUE18QVBQTElDQVRJT058MzYwMTExMjYy'
          category: Deployment
          type: BASIC
          version: ${{ github.event.release.tag_name }}
          user: ${{ github.actor }}
          description: inkstory app github
          shortDescription: inkstory-git
          commit: ${{ github.sha }}
          groupid: story-apps

