name: Change Tracking Marker
on:
  release:
    types:
      - published
  pull_request_target:
    types: 
     - closed
  deployment: 
permissions:
  contents: read
jobs:
  newrelic:
    runs-on: ubuntu-latest
    name: New Relic
    steps:
      - name: New Relic Application Deployment Marker
        uses: newrelic/deployment-marker-action@d88a59ea8f713ad6935e60de27273157790b1e3b # v2.6.2
        with:
          commandType: changeTrackingCreateEvent
          region: EU
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          entitySearch: id = 'ODU3NzkxNHxBUE18QVBQTElDQVRJT058MzYwMTExMjYy'
          category: Deployment
          type: BASIC
          version: ${{ github.event.number }}
          user: ${{ github.actor }}
          description: ${{github.repository}}
          shortDescription: ${{github.ref_name}}
          commit: ${{ github.sha }}
          groupid: ${{env.GROUP_ID}}

